// system_soc.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module system_soc (
		input  wire  clk_clk,           //          clk.clk
		input  wire  com_export_sda_in, //   com_export.sda_in
		input  wire  com_export_scl_in, //             .scl_in
		output wire  com_export_sda_oe, //             .sda_oe
		output wire  com_export_scl_oe, //             .scl_oe
		input  wire  debug_export_rxd,  // debug_export.rxd
		output wire  debug_export_txd,  //             .txd
		input  wire  reset_reset_n      //        reset.reset_n
	);

	wire  [31:0] cpu_data_manager_awaddr;                 // CPU:data_manager_awaddr -> mm_interconnect_0:CPU_data_manager_awaddr
	wire   [1:0] cpu_data_manager_bresp;                  // mm_interconnect_0:CPU_data_manager_bresp -> CPU:data_manager_bresp
	wire         cpu_data_manager_arready;                // mm_interconnect_0:CPU_data_manager_arready -> CPU:data_manager_arready
	wire  [31:0] cpu_data_manager_rdata;                  // mm_interconnect_0:CPU_data_manager_rdata -> CPU:data_manager_rdata
	wire   [3:0] cpu_data_manager_wstrb;                  // CPU:data_manager_wstrb -> mm_interconnect_0:CPU_data_manager_wstrb
	wire         cpu_data_manager_wready;                 // mm_interconnect_0:CPU_data_manager_wready -> CPU:data_manager_wready
	wire         cpu_data_manager_awready;                // mm_interconnect_0:CPU_data_manager_awready -> CPU:data_manager_awready
	wire         cpu_data_manager_rready;                 // CPU:data_manager_rready -> mm_interconnect_0:CPU_data_manager_rready
	wire         cpu_data_manager_bready;                 // CPU:data_manager_bready -> mm_interconnect_0:CPU_data_manager_bready
	wire         cpu_data_manager_wvalid;                 // CPU:data_manager_wvalid -> mm_interconnect_0:CPU_data_manager_wvalid
	wire  [31:0] cpu_data_manager_araddr;                 // CPU:data_manager_araddr -> mm_interconnect_0:CPU_data_manager_araddr
	wire   [2:0] cpu_data_manager_arprot;                 // CPU:data_manager_arprot -> mm_interconnect_0:CPU_data_manager_arprot
	wire   [1:0] cpu_data_manager_rresp;                  // mm_interconnect_0:CPU_data_manager_rresp -> CPU:data_manager_rresp
	wire   [2:0] cpu_data_manager_awprot;                 // CPU:data_manager_awprot -> mm_interconnect_0:CPU_data_manager_awprot
	wire  [31:0] cpu_data_manager_wdata;                  // CPU:data_manager_wdata -> mm_interconnect_0:CPU_data_manager_wdata
	wire         cpu_data_manager_arvalid;                // CPU:data_manager_arvalid -> mm_interconnect_0:CPU_data_manager_arvalid
	wire         cpu_data_manager_bvalid;                 // mm_interconnect_0:CPU_data_manager_bvalid -> CPU:data_manager_bvalid
	wire         cpu_data_manager_awvalid;                // CPU:data_manager_awvalid -> mm_interconnect_0:CPU_data_manager_awvalid
	wire         cpu_data_manager_rvalid;                 // mm_interconnect_0:CPU_data_manager_rvalid -> CPU:data_manager_rvalid
	wire  [31:0] cpu_instruction_manager_awaddr;          // CPU:instruction_manager_awaddr -> mm_interconnect_0:CPU_instruction_manager_awaddr
	wire   [1:0] cpu_instruction_manager_bresp;           // mm_interconnect_0:CPU_instruction_manager_bresp -> CPU:instruction_manager_bresp
	wire         cpu_instruction_manager_arready;         // mm_interconnect_0:CPU_instruction_manager_arready -> CPU:instruction_manager_arready
	wire  [31:0] cpu_instruction_manager_rdata;           // mm_interconnect_0:CPU_instruction_manager_rdata -> CPU:instruction_manager_rdata
	wire   [3:0] cpu_instruction_manager_wstrb;           // CPU:instruction_manager_wstrb -> mm_interconnect_0:CPU_instruction_manager_wstrb
	wire         cpu_instruction_manager_wready;          // mm_interconnect_0:CPU_instruction_manager_wready -> CPU:instruction_manager_wready
	wire         cpu_instruction_manager_awready;         // mm_interconnect_0:CPU_instruction_manager_awready -> CPU:instruction_manager_awready
	wire         cpu_instruction_manager_rready;          // CPU:instruction_manager_rready -> mm_interconnect_0:CPU_instruction_manager_rready
	wire         cpu_instruction_manager_bready;          // CPU:instruction_manager_bready -> mm_interconnect_0:CPU_instruction_manager_bready
	wire         cpu_instruction_manager_wvalid;          // CPU:instruction_manager_wvalid -> mm_interconnect_0:CPU_instruction_manager_wvalid
	wire  [31:0] cpu_instruction_manager_araddr;          // CPU:instruction_manager_araddr -> mm_interconnect_0:CPU_instruction_manager_araddr
	wire   [2:0] cpu_instruction_manager_arprot;          // CPU:instruction_manager_arprot -> mm_interconnect_0:CPU_instruction_manager_arprot
	wire   [1:0] cpu_instruction_manager_rresp;           // mm_interconnect_0:CPU_instruction_manager_rresp -> CPU:instruction_manager_rresp
	wire   [2:0] cpu_instruction_manager_awprot;          // CPU:instruction_manager_awprot -> mm_interconnect_0:CPU_instruction_manager_awprot
	wire  [31:0] cpu_instruction_manager_wdata;           // CPU:instruction_manager_wdata -> mm_interconnect_0:CPU_instruction_manager_wdata
	wire         cpu_instruction_manager_arvalid;         // CPU:instruction_manager_arvalid -> mm_interconnect_0:CPU_instruction_manager_arvalid
	wire         cpu_instruction_manager_bvalid;          // mm_interconnect_0:CPU_instruction_manager_bvalid -> CPU:instruction_manager_bvalid
	wire         cpu_instruction_manager_awvalid;         // CPU:instruction_manager_awvalid -> mm_interconnect_0:CPU_instruction_manager_awvalid
	wire         cpu_instruction_manager_rvalid;          // mm_interconnect_0:CPU_instruction_manager_rvalid -> CPU:instruction_manager_rvalid
	wire  [31:0] mm_interconnect_0_i2c_csr_readdata;      // I2C:readdata -> mm_interconnect_0:I2C_csr_readdata
	wire   [3:0] mm_interconnect_0_i2c_csr_address;       // mm_interconnect_0:I2C_csr_address -> I2C:addr
	wire         mm_interconnect_0_i2c_csr_read;          // mm_interconnect_0:I2C_csr_read -> I2C:read
	wire         mm_interconnect_0_i2c_csr_write;         // mm_interconnect_0:I2C_csr_write -> I2C:write
	wire  [31:0] mm_interconnect_0_i2c_csr_writedata;     // mm_interconnect_0:I2C_csr_writedata -> I2C:writedata
	wire         mm_interconnect_0_sram_s1_chipselect;    // mm_interconnect_0:SRAM_s1_chipselect -> SRAM:chipselect
	wire  [31:0] mm_interconnect_0_sram_s1_readdata;      // SRAM:readdata -> mm_interconnect_0:SRAM_s1_readdata
	wire  [12:0] mm_interconnect_0_sram_s1_address;       // mm_interconnect_0:SRAM_s1_address -> SRAM:address
	wire   [3:0] mm_interconnect_0_sram_s1_byteenable;    // mm_interconnect_0:SRAM_s1_byteenable -> SRAM:byteenable
	wire         mm_interconnect_0_sram_s1_write;         // mm_interconnect_0:SRAM_s1_write -> SRAM:write
	wire  [31:0] mm_interconnect_0_sram_s1_writedata;     // mm_interconnect_0:SRAM_s1_writedata -> SRAM:writedata
	wire         mm_interconnect_0_sram_s1_clken;         // mm_interconnect_0:SRAM_s1_clken -> SRAM:clken
	wire         mm_interconnect_0_uart_s1_chipselect;    // mm_interconnect_0:UART_s1_chipselect -> UART:chipselect
	wire  [15:0] mm_interconnect_0_uart_s1_readdata;      // UART:readdata -> mm_interconnect_0:UART_s1_readdata
	wire   [2:0] mm_interconnect_0_uart_s1_address;       // mm_interconnect_0:UART_s1_address -> UART:address
	wire         mm_interconnect_0_uart_s1_read;          // mm_interconnect_0:UART_s1_read -> UART:read_n
	wire         mm_interconnect_0_uart_s1_begintransfer; // mm_interconnect_0:UART_s1_begintransfer -> UART:begintransfer
	wire         mm_interconnect_0_uart_s1_write;         // mm_interconnect_0:UART_s1_write -> UART:write_n
	wire  [15:0] mm_interconnect_0_uart_s1_writedata;     // mm_interconnect_0:UART_s1_writedata -> UART:writedata
	wire         mm_interconnect_0_timer_s1_chipselect;   // mm_interconnect_0:TIMER_s1_chipselect -> TIMER:chipselect
	wire  [15:0] mm_interconnect_0_timer_s1_readdata;     // TIMER:readdata -> mm_interconnect_0:TIMER_s1_readdata
	wire   [2:0] mm_interconnect_0_timer_s1_address;      // mm_interconnect_0:TIMER_s1_address -> TIMER:address
	wire         mm_interconnect_0_timer_s1_write;        // mm_interconnect_0:TIMER_s1_write -> TIMER:write_n
	wire  [15:0] mm_interconnect_0_timer_s1_writedata;    // mm_interconnect_0:TIMER_s1_writedata -> TIMER:writedata
	wire         rst_controller_reset_out_reset;          // rst_controller:reset_out -> [CPU:reset_reset, I2C:rst_n, SRAM:reset, TIMER:reset_n, UART:reset_n, mm_interconnect_0:CPU_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;      // rst_controller:reset_req -> [SRAM:reset_req, rst_translator:reset_req_in]

	system_soc_CPU cpu (
		.clk                         (clk_clk),                         //                 clk.clk
		.reset_reset                 (rst_controller_reset_out_reset),  //               reset.reset
		.instruction_manager_awaddr  (cpu_instruction_manager_awaddr),  // instruction_manager.awaddr
		.instruction_manager_awprot  (cpu_instruction_manager_awprot),  //                    .awprot
		.instruction_manager_awvalid (cpu_instruction_manager_awvalid), //                    .awvalid
		.instruction_manager_awready (cpu_instruction_manager_awready), //                    .awready
		.instruction_manager_wdata   (cpu_instruction_manager_wdata),   //                    .wdata
		.instruction_manager_wstrb   (cpu_instruction_manager_wstrb),   //                    .wstrb
		.instruction_manager_wvalid  (cpu_instruction_manager_wvalid),  //                    .wvalid
		.instruction_manager_wready  (cpu_instruction_manager_wready),  //                    .wready
		.instruction_manager_bresp   (cpu_instruction_manager_bresp),   //                    .bresp
		.instruction_manager_bvalid  (cpu_instruction_manager_bvalid),  //                    .bvalid
		.instruction_manager_bready  (cpu_instruction_manager_bready),  //                    .bready
		.instruction_manager_araddr  (cpu_instruction_manager_araddr),  //                    .araddr
		.instruction_manager_arprot  (cpu_instruction_manager_arprot),  //                    .arprot
		.instruction_manager_arvalid (cpu_instruction_manager_arvalid), //                    .arvalid
		.instruction_manager_arready (cpu_instruction_manager_arready), //                    .arready
		.instruction_manager_rdata   (cpu_instruction_manager_rdata),   //                    .rdata
		.instruction_manager_rresp   (cpu_instruction_manager_rresp),   //                    .rresp
		.instruction_manager_rvalid  (cpu_instruction_manager_rvalid),  //                    .rvalid
		.instruction_manager_rready  (cpu_instruction_manager_rready),  //                    .rready
		.data_manager_awaddr         (cpu_data_manager_awaddr),         //        data_manager.awaddr
		.data_manager_awprot         (cpu_data_manager_awprot),         //                    .awprot
		.data_manager_awvalid        (cpu_data_manager_awvalid),        //                    .awvalid
		.data_manager_awready        (cpu_data_manager_awready),        //                    .awready
		.data_manager_wdata          (cpu_data_manager_wdata),          //                    .wdata
		.data_manager_wstrb          (cpu_data_manager_wstrb),          //                    .wstrb
		.data_manager_wvalid         (cpu_data_manager_wvalid),         //                    .wvalid
		.data_manager_wready         (cpu_data_manager_wready),         //                    .wready
		.data_manager_bresp          (cpu_data_manager_bresp),          //                    .bresp
		.data_manager_bvalid         (cpu_data_manager_bvalid),         //                    .bvalid
		.data_manager_bready         (cpu_data_manager_bready),         //                    .bready
		.data_manager_araddr         (cpu_data_manager_araddr),         //                    .araddr
		.data_manager_arprot         (cpu_data_manager_arprot),         //                    .arprot
		.data_manager_arvalid        (cpu_data_manager_arvalid),        //                    .arvalid
		.data_manager_arready        (cpu_data_manager_arready),        //                    .arready
		.data_manager_rdata          (cpu_data_manager_rdata),          //                    .rdata
		.data_manager_rresp          (cpu_data_manager_rresp),          //                    .rresp
		.data_manager_rvalid         (cpu_data_manager_rvalid),         //                    .rvalid
		.data_manager_rready         (cpu_data_manager_rready)          //                    .rready
	);

	altera_avalon_i2c #(
		.USE_AV_ST       (0),
		.FIFO_DEPTH      (32),
		.FIFO_DEPTH_LOG2 (5)
	) i2c (
		.clk       (clk_clk),                             //            clock.clk
		.rst_n     (~rst_controller_reset_out_reset),     //       reset_sink.reset_n
		.intr      (),                                    // interrupt_sender.irq
		.addr      (mm_interconnect_0_i2c_csr_address),   //              csr.address
		.read      (mm_interconnect_0_i2c_csr_read),      //                 .read
		.write     (mm_interconnect_0_i2c_csr_write),     //                 .write
		.writedata (mm_interconnect_0_i2c_csr_writedata), //                 .writedata
		.readdata  (mm_interconnect_0_i2c_csr_readdata),  //                 .readdata
		.sda_in    (com_export_sda_in),                   //       i2c_serial.sda_in
		.scl_in    (com_export_scl_in),                   //                 .scl_in
		.sda_oe    (com_export_sda_oe),                   //                 .sda_oe
		.scl_oe    (com_export_scl_oe),                   //                 .scl_oe
		.src_data  (),                                    //      (terminated)
		.src_valid (),                                    //      (terminated)
		.src_ready (1'b0),                                //      (terminated)
		.snk_data  (16'b0000000000000000),                //      (terminated)
		.snk_valid (1'b0),                                //      (terminated)
		.snk_ready ()                                     //      (terminated)
	);

	system_soc_SRAM sram (
		.clk        (clk_clk),                              //   clk1.clk
		.address    (mm_interconnect_0_sram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_sram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_sram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_sram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_sram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_sram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_sram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),       // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),   //       .reset_req
		.freeze     (1'b0)                                  // (terminated)
	);

	system_soc_TIMER timer (
		.clk        (clk_clk),                               //   clk.clk
		.reset_n    (~rst_controller_reset_out_reset),       // reset.reset_n
		.address    (mm_interconnect_0_timer_s1_address),    //    s1.address
		.writedata  (mm_interconnect_0_timer_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_0_timer_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_0_timer_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_0_timer_s1_write),     //      .write_n
		.irq        ()                                       //   irq.irq
	);

	system_soc_UART uart (
		.clk           (clk_clk),                                 //                 clk.clk
		.reset_n       (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address       (mm_interconnect_0_uart_s1_address),       //                  s1.address
		.begintransfer (mm_interconnect_0_uart_s1_begintransfer), //                    .begintransfer
		.chipselect    (mm_interconnect_0_uart_s1_chipselect),    //                    .chipselect
		.read_n        (~mm_interconnect_0_uart_s1_read),         //                    .read_n
		.write_n       (~mm_interconnect_0_uart_s1_write),        //                    .write_n
		.writedata     (mm_interconnect_0_uart_s1_writedata),     //                    .writedata
		.readdata      (mm_interconnect_0_uart_s1_readdata),      //                    .readdata
		.rxd           (debug_export_rxd),                        // external_connection.export
		.txd           (debug_export_txd),                        //                    .export
		.irq           ()                                         //                 irq.irq
	);

	system_soc_mm_interconnect_0 mm_interconnect_0 (
		.CPU_data_manager_awaddr               (cpu_data_manager_awaddr),                 //                CPU_data_manager.awaddr
		.CPU_data_manager_awprot               (cpu_data_manager_awprot),                 //                                .awprot
		.CPU_data_manager_awvalid              (cpu_data_manager_awvalid),                //                                .awvalid
		.CPU_data_manager_awready              (cpu_data_manager_awready),                //                                .awready
		.CPU_data_manager_wdata                (cpu_data_manager_wdata),                  //                                .wdata
		.CPU_data_manager_wstrb                (cpu_data_manager_wstrb),                  //                                .wstrb
		.CPU_data_manager_wvalid               (cpu_data_manager_wvalid),                 //                                .wvalid
		.CPU_data_manager_wready               (cpu_data_manager_wready),                 //                                .wready
		.CPU_data_manager_bresp                (cpu_data_manager_bresp),                  //                                .bresp
		.CPU_data_manager_bvalid               (cpu_data_manager_bvalid),                 //                                .bvalid
		.CPU_data_manager_bready               (cpu_data_manager_bready),                 //                                .bready
		.CPU_data_manager_araddr               (cpu_data_manager_araddr),                 //                                .araddr
		.CPU_data_manager_arprot               (cpu_data_manager_arprot),                 //                                .arprot
		.CPU_data_manager_arvalid              (cpu_data_manager_arvalid),                //                                .arvalid
		.CPU_data_manager_arready              (cpu_data_manager_arready),                //                                .arready
		.CPU_data_manager_rdata                (cpu_data_manager_rdata),                  //                                .rdata
		.CPU_data_manager_rresp                (cpu_data_manager_rresp),                  //                                .rresp
		.CPU_data_manager_rvalid               (cpu_data_manager_rvalid),                 //                                .rvalid
		.CPU_data_manager_rready               (cpu_data_manager_rready),                 //                                .rready
		.CPU_instruction_manager_awaddr        (cpu_instruction_manager_awaddr),          //         CPU_instruction_manager.awaddr
		.CPU_instruction_manager_awprot        (cpu_instruction_manager_awprot),          //                                .awprot
		.CPU_instruction_manager_awvalid       (cpu_instruction_manager_awvalid),         //                                .awvalid
		.CPU_instruction_manager_awready       (cpu_instruction_manager_awready),         //                                .awready
		.CPU_instruction_manager_wdata         (cpu_instruction_manager_wdata),           //                                .wdata
		.CPU_instruction_manager_wstrb         (cpu_instruction_manager_wstrb),           //                                .wstrb
		.CPU_instruction_manager_wvalid        (cpu_instruction_manager_wvalid),          //                                .wvalid
		.CPU_instruction_manager_wready        (cpu_instruction_manager_wready),          //                                .wready
		.CPU_instruction_manager_bresp         (cpu_instruction_manager_bresp),           //                                .bresp
		.CPU_instruction_manager_bvalid        (cpu_instruction_manager_bvalid),          //                                .bvalid
		.CPU_instruction_manager_bready        (cpu_instruction_manager_bready),          //                                .bready
		.CPU_instruction_manager_araddr        (cpu_instruction_manager_araddr),          //                                .araddr
		.CPU_instruction_manager_arprot        (cpu_instruction_manager_arprot),          //                                .arprot
		.CPU_instruction_manager_arvalid       (cpu_instruction_manager_arvalid),         //                                .arvalid
		.CPU_instruction_manager_arready       (cpu_instruction_manager_arready),         //                                .arready
		.CPU_instruction_manager_rdata         (cpu_instruction_manager_rdata),           //                                .rdata
		.CPU_instruction_manager_rresp         (cpu_instruction_manager_rresp),           //                                .rresp
		.CPU_instruction_manager_rvalid        (cpu_instruction_manager_rvalid),          //                                .rvalid
		.CPU_instruction_manager_rready        (cpu_instruction_manager_rready),          //                                .rready
		.CLK_clk_clk                           (clk_clk),                                 //                         CLK_clk.clk
		.CPU_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),          // CPU_reset_reset_bridge_in_reset.reset
		.I2C_csr_address                       (mm_interconnect_0_i2c_csr_address),       //                         I2C_csr.address
		.I2C_csr_write                         (mm_interconnect_0_i2c_csr_write),         //                                .write
		.I2C_csr_read                          (mm_interconnect_0_i2c_csr_read),          //                                .read
		.I2C_csr_readdata                      (mm_interconnect_0_i2c_csr_readdata),      //                                .readdata
		.I2C_csr_writedata                     (mm_interconnect_0_i2c_csr_writedata),     //                                .writedata
		.SRAM_s1_address                       (mm_interconnect_0_sram_s1_address),       //                         SRAM_s1.address
		.SRAM_s1_write                         (mm_interconnect_0_sram_s1_write),         //                                .write
		.SRAM_s1_readdata                      (mm_interconnect_0_sram_s1_readdata),      //                                .readdata
		.SRAM_s1_writedata                     (mm_interconnect_0_sram_s1_writedata),     //                                .writedata
		.SRAM_s1_byteenable                    (mm_interconnect_0_sram_s1_byteenable),    //                                .byteenable
		.SRAM_s1_chipselect                    (mm_interconnect_0_sram_s1_chipselect),    //                                .chipselect
		.SRAM_s1_clken                         (mm_interconnect_0_sram_s1_clken),         //                                .clken
		.TIMER_s1_address                      (mm_interconnect_0_timer_s1_address),      //                        TIMER_s1.address
		.TIMER_s1_write                        (mm_interconnect_0_timer_s1_write),        //                                .write
		.TIMER_s1_readdata                     (mm_interconnect_0_timer_s1_readdata),     //                                .readdata
		.TIMER_s1_writedata                    (mm_interconnect_0_timer_s1_writedata),    //                                .writedata
		.TIMER_s1_chipselect                   (mm_interconnect_0_timer_s1_chipselect),   //                                .chipselect
		.UART_s1_address                       (mm_interconnect_0_uart_s1_address),       //                         UART_s1.address
		.UART_s1_write                         (mm_interconnect_0_uart_s1_write),         //                                .write
		.UART_s1_read                          (mm_interconnect_0_uart_s1_read),          //                                .read
		.UART_s1_readdata                      (mm_interconnect_0_uart_s1_readdata),      //                                .readdata
		.UART_s1_writedata                     (mm_interconnect_0_uart_s1_writedata),     //                                .writedata
		.UART_s1_begintransfer                 (mm_interconnect_0_uart_s1_begintransfer), //                                .begintransfer
		.UART_s1_chipselect                    (mm_interconnect_0_uart_s1_chipselect)     //                                .chipselect
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
